"use strict";
/*
    app.js, main Angular application script
    define your module and controllers here
*/

angular.module('CommentsApp', [])
    .config(function($httpProvider) {
        //Parse required two extra headers sent with every HTTP request: X-Parse-Application-Id, X-Parse-REST-API-Key
        //the first needs to be set to your application's ID value
        //the second needs to be set to your application's REST API key
        //both of these are generated by Parse when you create your application via their web site
        //the following lines will add these as default headers so that they are sent with every
        //HTTP request we make in this application
        $httpProvider.defaults.headers.common['X-Parse-Application-Id'] = 'wy0PRVgjKsa5OO84Ln8fBlVFxARrKzYVaE8vZuh7';
        $httpProvider.defaults.headers.common['X-Parse-REST-API-Key'] = 'jFmZWR5JNspmRDtweaThT5iTUFiPN2VF6hPScgrF';
    })
    .controller('CommentsController', function($scope, $http) {
        //this is the base URL for all comment objects managed by your application
        //requesting this with a GET will get all comments objects
        //sending a POST to this will insert a new comment object
        //sending a PUT to this URL + '/' + comment.objectId will update an existing comment
        //sending a DELETE to this URL + '/' + comment.objectId will delete an existing comment
        var commentsUrl = 'https://api.parse.com/1/classes/comments';

        $scope.refreshComments = function() {
            //get all comments
            $scope.loading = true;
            $http.get(commentsUrl)
                .success(function(responseData) {
                    //when returning a list of data, Parse will always return an
                    //object with one property called 'results', which will contain an
                    //array containing all the data objects
                    $scope.comments = responseData.results;
                })
                .error(function(err) {
                    console.log(err);
                    //notify user in some way
                })
                .finally(function() {
                    $scope.loading = false;
                });
        }; //$scope.refreshComments()

        $scope.refreshComments();

        //initialize a new comment object on the scope for the new comment form
        $scope.newComment = {score: 0};

        $scope.addComment = function(comment) {
            $scope.inserting = true;
            $http.post(commentsUrl, comment)
                .success(function(responseData) {
                    //Parse will return the new objectId in the response data
                    //copy that to the comment we just inserted
                    comment.objectId = responseData.objectId;

                    //and add that comment to our comment list
                    $scope.comments.push(comment);

                    $scope.newComment = {score: 0};

                })
                .error(function(err) {
                    console.log(err);
                    //report to user in some way
                })
                .finally(function() {
                    $scope.inserting = false;
                });
        };

        $scope.updateComment = function(comment) {
            $scope.updating = true;
            $http.put(commentsUrl + '/' + comment.objectId, comment)
                .success(function(responseData) {
                    //nothing we really need to do since local object is already up-to-date
                })
                .error(function(err) {
                    console.log(err);
                    //notify user in some way
                })
                .finally(function() {
                    $scope.updating = false;
                });
        };

    });
